AWSTemplateFormatVersion: 2010-09-09
Description: >-
  yeet

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        DEBUG: true
        WebhookUrl: '{{resolve:ssm:WebhookUrl:1}}'
        # AccessKey: '{{resolve:ssm:AccessKey:1}}'
        # SecretKey: '{{resolve:ssm:SecretKey:1}}'

Resources:
  Throttler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: dist/function.handler
      Runtime: nodejs12.x
      ReservedConcurrentExecutions: 1
      Events:
        Throttler:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:ap-southeast-2:355151872526:throttle-reg
            BatchSize: 1
      Role: arn:aws:iam::355151872526:role/joeslambda

Outputs:
  Throttler:
    Description: dylan brady invented music 2.0
    Value: !GetAtt Throttler.Arn